# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AlertDetailsOverride(Model):
    """Settings for how to dynamically override alert static details.

    :param alert_display_name_format: the format containing columns name(s) to
     override the alert name
    :type alert_display_name_format: str
    :param alert_description_format: the format containing columns name(s) to
     override the alert description
    :type alert_description_format: str
    :param alert_tactics_column_name: the column name to take the alert
     tactics from
    :type alert_tactics_column_name: str
    :param alert_severity_column_name: the column name to take the alert
     severity from
    :type alert_severity_column_name: str
    """

    _attribute_map = {
        'alert_display_name_format': {'key': 'alertDisplayNameFormat', 'type': 'str'},
        'alert_description_format': {'key': 'alertDescriptionFormat', 'type': 'str'},
        'alert_tactics_column_name': {'key': 'alertTacticsColumnName', 'type': 'str'},
        'alert_severity_column_name': {'key': 'alertSeverityColumnName', 'type': 'str'},
    }

    def __init__(self, *, alert_display_name_format: str=None, alert_description_format: str=None, alert_tactics_column_name: str=None, alert_severity_column_name: str=None, **kwargs) -> None:
        super(AlertDetailsOverride, self).__init__(**kwargs)
        self.alert_display_name_format = alert_display_name_format
        self.alert_description_format = alert_description_format
        self.alert_tactics_column_name = alert_tactics_column_name
        self.alert_severity_column_name = alert_severity_column_name
