# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EntityMapping(Model):
    """Single entity mapping for the alert rule.

    :param entity_type: Possible values include: 'Account', 'Host', 'IP',
     'Malware', 'File', 'Process', 'CloudApplication', 'DNS', 'AzureResource',
     'FileHash', 'RegistryKey', 'RegistryValue', 'SecurityGroup', 'URL',
     'Mailbox', 'MailCluster', 'MailMessage', 'SubmissionMail'
    :type entity_type: str or ~alertrules.models.EntityMappingType
    :param field_mappings: array of field mappings for the given entity
     mapping
    :type field_mappings: list[~alertrules.models.FieldMapping]
    """

    _attribute_map = {
        'entity_type': {'key': 'entityType', 'type': 'str'},
        'field_mappings': {'key': 'fieldMappings', 'type': '[FieldMapping]'},
    }

    def __init__(self, *, entity_type=None, field_mappings=None, **kwargs) -> None:
        super(EntityMapping, self).__init__(**kwargs)
        self.entity_type = entity_type
        self.field_mappings = field_mappings
