# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FieldMapping(Model):
    """A single field mapping of the mapped entity.

    :param identifier: the V3 identifier of the entity
    :type identifier: str
    :param column_name: the column name to be mapped to the identifier
    :type column_name: str
    """

    _attribute_map = {
        'identifier': {'key': 'identifier', 'type': 'str'},
        'column_name': {'key': 'columnName', 'type': 'str'},
    }

    def __init__(self, *, identifier: str=None, column_name: str=None, **kwargs) -> None:
        super(FieldMapping, self).__init__(**kwargs)
        self.identifier = identifier
        self.column_name = column_name
