# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GroupingConfiguration(Model):
    """Grouping configuration property bag.

    All required parameters must be populated in order to send to Azure.

    :param enabled: Required. Grouping enabled
    :type enabled: bool
    :param reopen_closed_incident: Required. Re-open closed matching incidents
    :type reopen_closed_incident: bool
    :param lookback_duration: Required. Limit the group to alerts created
     within the lookback duration (in ISO 8601 duration format)
    :type lookback_duration: timedelta
    :param matching_method: Required. Grouping matching method. When method is
     Selected at least one of groupByEntities, groupByAlertDetails,
     groupByCustomDetails must be provided and not empty. Possible values
     include: 'AllEntities', 'AnyAlert', 'Selected'
    :type matching_method: str or ~alertrules.models.MatchingMethod
    :param group_by_entities: A list of entity types to group by (when
     matchingMethod is Selected). Only entities defined in the current alert
     rule may be used.
    :type group_by_entities: list[str or ~alertrules.models.EntityMappingType]
    :param group_by_alert_details: A list of alert details to group by (when
     matchingMethod is Selected)
    :type group_by_alert_details: list[str or ~alertrules.models.AlertDetail]
    :param group_by_custom_details: A list of custom details keys to group by
     (when matchingMethod is Selected). Only keys defined in the current alert
     rule may be used.
    :type group_by_custom_details: list[str]
    """

    _validation = {
        'enabled': {'required': True},
        'reopen_closed_incident': {'required': True},
        'lookback_duration': {'required': True},
        'matching_method': {'required': True},
    }

    _attribute_map = {
        'enabled': {'key': 'enabled', 'type': 'bool'},
        'reopen_closed_incident': {'key': 'reopenClosedIncident', 'type': 'bool'},
        'lookback_duration': {'key': 'lookbackDuration', 'type': 'duration'},
        'matching_method': {'key': 'matchingMethod', 'type': 'str'},
        'group_by_entities': {'key': 'groupByEntities', 'type': '[str]'},
        'group_by_alert_details': {'key': 'groupByAlertDetails', 'type': '[str]'},
        'group_by_custom_details': {'key': 'groupByCustomDetails', 'type': '[str]'},
    }

    def __init__(self, *, enabled: bool, reopen_closed_incident: bool, lookback_duration, matching_method, group_by_entities=None, group_by_alert_details=None, group_by_custom_details=None, **kwargs) -> None:
        super(GroupingConfiguration, self).__init__(**kwargs)
        self.enabled = enabled
        self.reopen_closed_incident = reopen_closed_incident
        self.lookback_duration = lookback_duration
        self.matching_method = matching_method
        self.group_by_entities = group_by_entities
        self.group_by_alert_details = group_by_alert_details
        self.group_by_custom_details = group_by_custom_details
