# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class AlertRuleKind(str, Enum):

    scheduled = "Scheduled"
    microsoft_security_incident_creation = "MicrosoftSecurityIncidentCreation"
    fusion = "Fusion"
    ml_behavior_analytics = "MLBehaviorAnalytics"
    threat_intelligence = "ThreatIntelligence"


class TemplateStatus(str, Enum):

    installed = "Installed"  #: Alert rule template installed. and can not use more then once
    available = "Available"  #: Alert rule template is available.
    not_available = "NotAvailable"  #: Alert rule template is not available


class TriggerOperator(str, Enum):

    greater_than = "GreaterThan"
    less_than = "LessThan"
    equal = "Equal"
    not_equal = "NotEqual"


class AlertSeverity(str, Enum):

    high = "High"  #: High severity
    medium = "Medium"  #: Medium severity
    low = "Low"  #: Low severity
    informational = "Informational"  #: Informational severity


class AttackTactic(str, Enum):

    initial_access = "InitialAccess"
    execution = "Execution"
    persistence = "Persistence"
    privilege_escalation = "PrivilegeEscalation"
    defense_evasion = "DefenseEvasion"
    credential_access = "CredentialAccess"
    discovery = "Discovery"
    lateral_movement = "LateralMovement"
    collection = "Collection"
    exfiltration = "Exfiltration"
    command_and_control = "CommandAndControl"
    impact = "Impact"
    pre_attack = "PreAttack"


class MicrosoftSecurityProductName(str, Enum):

    microsoft_cloud_app_security = "Microsoft Cloud App Security"
    azure_security_center = "Azure Security Center"
    azure_advanced_threat_protection = "Azure Advanced Threat Protection"
    azure_active_directory_identity_protection = "Azure Active Directory Identity Protection"
    azure_security_centerfor_io_t = "Azure Security Center for IoT"
    office365_advanced_threat_protection = "Office 365 Advanced Threat Protection"
    microsoft_defender_advanced_threat_protection = "Microsoft Defender Advanced Threat Protection"


class MatchingMethod(str, Enum):

    all_entities = "AllEntities"  #: Grouping alerts into a single incident if all the entities match
    any_alert = "AnyAlert"  #: Grouping any alerts triggered by this rule into a single incident
    selected = "Selected"  #: Grouping alerts into a single incident if the selected entities, custom details and alert details match


class EntityMappingType(str, Enum):

    account = "Account"  #: User account entity type
    host = "Host"  #: Host entity type
    ip = "IP"  #: IP address entity type
    malware = "Malware"  #: Malware entity type
    file = "File"  #: System file entity type
    process = "Process"  #: Process entity type
    cloud_application = "CloudApplication"  #: Cloud app entity type
    dns = "DNS"  #: DNS entity type
    azure_resource = "AzureResource"  #: Azure resource entity type
    file_hash = "FileHash"  #: File-hash entity type
    registry_key = "RegistryKey"  #: Registry key entity type
    registry_value = "RegistryValue"  #: Registry value entity type
    security_group = "SecurityGroup"  #: Security group entity type
    url = "URL"  #: URL entity type
    mailbox = "Mailbox"  #: Mailbox entity type
    mail_cluster = "MailCluster"  #: Mail cluster entity type
    mail_message = "MailMessage"  #: Mail message entity type
    submission_mail = "SubmissionMail"  #: Submission mail entity type


class AlertDetail(str, Enum):

    display_name = "DisplayName"  #: Alert display name
    severity = "Severity"  #: Alert severity


class EventGroupingAggregationKind(str, Enum):

    single_alert = "SingleAlert"
    alert_per_result = "AlertPerResult"


class CreatedByType(str, Enum):

    user = "User"
    application = "Application"
    managed_identity = "ManagedIdentity"
    key = "Key"
